AWSTemplateFormatVersion: "2010-09-09"
Description: Artifact Bucket

Parameters:
  ExpirationInDays:
    Description: Log Expiration In Days
    Type: Number
    Default: 7

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: !Ref ExpirationInDays
            Status: Enabled

Outputs:
  BucketName:
    Description: Artifact Bucket Name
    Value: !Ref Bucket
    Export:
      Name: !Sub "${AWS::StackName}-bucket-name"
